// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKAesf0LkQG8E43hpD7j-6srPqCGrXgvA',
    appId: '1:168471617872:web:b5ddbd8860098f8b864c55',
    messagingSenderId: '168471617872',
    projectId: 'mulil26-mobileprogramming-p10',
    authDomain: 'mulil26-mobileprogramming-p10.firebaseapp.com',
    storageBucket: 'mulil26-mobileprogramming-p10.firebasestorage.app',
    measurementId: 'G-VEYSW6M1JM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7wobq-TgPu1phR_EZNb1bmieiZFVwmEo',
    appId: '1:168471617872:android:c62551f4d9a51ecc864c55',
    messagingSenderId: '168471617872',
    projectId: 'mulil26-mobileprogramming-p10',
    storageBucket: 'mulil26-mobileprogramming-p10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsUDd8DVlNL3owoU6_eFFUH37If7VJ9tY',
    appId: '1:168471617872:ios:77a22f4ad696011d864c55',
    messagingSenderId: '168471617872',
    projectId: 'mulil26-mobileprogramming-p10',
    storageBucket: 'mulil26-mobileprogramming-p10.firebasestorage.app',
    iosBundleId: 'com.example.mobileprogrammingPertemuan10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsUDd8DVlNL3owoU6_eFFUH37If7VJ9tY',
    appId: '1:168471617872:ios:77a22f4ad696011d864c55',
    messagingSenderId: '168471617872',
    projectId: 'mulil26-mobileprogramming-p10',
    storageBucket: 'mulil26-mobileprogramming-p10.firebasestorage.app',
    iosBundleId: 'com.example.mobileprogrammingPertemuan10',
  );
}
